services:
  db:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci